### PR TITLE
Command aliases added

### PR DESCRIPTION
**Pull request by TanYikai**

### CODE REVIEW

**Comment by Xenonym** [comment]
@TanYikai, is the `sort` command a separate enhancement apart from the command aliases?

**Comment by TanYikai** [comment]
Yeap the sort is seperate de

**Comment by Xenonym** [comment]
@TanYikai possible to make a separate pull request for sort command? and also need to write tests for it (doesn't have to be this week though!)

Minimally, just have this pull requests be of one thing only (the command aliases).

**Comment by TanYikai** [comment]
Ok I'll do I'll do it tmr

**Review by Xenonym — APPROVED** [review]
Aliases added!

**Pull request merged**
